-- Premium Banking Management System PostgreSQL Script
-- Create database manually in pgAdmin if needed:
-- CREATE DATABASE "BMS";
-- Then open BMS > Query Tool and run this script.

DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS bank_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'STAFF', 'CUSTOMER')),
    phone VARCHAR(20),
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    account_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('SAVINGS', 'CURRENT')),
    balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00 CHECK (balance >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACTIVE', 'FROZEN', 'CLOSED', 'REJECTED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    transaction_id SERIAL PRIMARY KEY,
    from_account_id INT REFERENCES accounts(account_id),
    to_account_id INT REFERENCES accounts(account_id),
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER')),
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    description VARCHAR(255),
    is_reverted BOOLEAN DEFAULT FALSE,
    reversed_transaction_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bank_settings (
    id INT PRIMARY KEY DEFAULT 1,
    bank_name VARCHAR(120) NOT NULL DEFAULT 'Aurora Bank',
    logo_path VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (id = 1)
);

-- Passwords are SHA-256 hashes generated by PasswordUtil.java
-- admin123    = 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
-- staff123    = 10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6
-- customer123 = b041c0aeb35bb0fa4aa668ca5a920b590196fdaf9a00eb852c9b7f4d123cc6d6

INSERT INTO users(user_id, full_name, email, password, role, phone, address) VALUES
(1, 'Bank Admin', 'admin@bank.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'ADMIN', '9999999999', 'Head Office'),
(2, 'Demo Customer', 'customer@bank.com', 'b041c0aeb35bb0fa4aa668ca5a920b590196fdaf9a00eb852c9b7f4d123cc6d6', 'CUSTOMER', '8888888888', 'Demo City'),
(3, 'Second Customer', 'customer2@bank.com', 'b041c0aeb35bb0fa4aa668ca5a920b590196fdaf9a00eb852c9b7f4d123cc6d6', 'CUSTOMER', '7777777777', 'Sample City'),
(4, 'Demo Staff', 'staff@bank.com', '10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6', 'STAFF', '6666666666', 'Branch Office');

INSERT INTO accounts(account_id, user_id, account_number, account_type, balance, status) VALUES
(1, 2, '100000000002', 'SAVINGS', 5000.00, 'ACTIVE'),
(2, 3, '100000000003', 'SAVINGS', 3000.00, 'ACTIVE');

INSERT INTO transactions(transaction_id, from_account_id, to_account_id, transaction_type, amount, description) VALUES
(1, NULL, 1, 'DEPOSIT', 5000.00, 'Opening deposit'),
(2, NULL, 2, 'DEPOSIT', 3000.00, 'Opening deposit');

INSERT INTO bank_settings(id, bank_name, logo_path) VALUES
(1, 'Aurora Bank', NULL);

SELECT setval(pg_get_serial_sequence('users', 'user_id'), (SELECT MAX(user_id) FROM users));
SELECT setval(pg_get_serial_sequence('accounts', 'account_id'), (SELECT MAX(account_id) FROM accounts));
SELECT setval(pg_get_serial_sequence('transactions', 'transaction_id'), (SELECT MAX(transaction_id) FROM transactions));
